"""The answering agent.

Ask it a question about the transaction and it answers from the document and the
model, citing section ids. Two backends:

* `ClaudeAnswerer` - Claude with the tools in `tools.py`. Set ANTHROPIC_API_KEY.
* `OfflineAnswerer` - a deterministic, rule-based answerer over the same tools,
  so the agent is useful (and testable) with no key and no network. It routes on
  keywords and says so; it does not pretend to be the model.

Both are grounded in the same place: no number is generated by a language model,
it is computed in `terms.py` / `waterfall.py` and quoted.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Any, Protocol

from . import tools
from .findings import FINDINGS
from .terms import DealTerms, derive, pref_consistency

DEFAULT_MODEL = os.environ.get("DEAL_AGENT_MODEL", "claude-opus-5")

SYSTEM_PROMPT = """You are the answering agent for a single document: a term sheet for \
NLP's purchase of $35M of secondary exposure to fund SB2 (a Mauritius vehicle) from its \
existing Class B LPs, structured through a Singapore feeder (NLPF) and an India fund (NLPI).

You answer questions about this transaction for the people negotiating it. They know the \
domain; they need precision, not education.

How to work:
- Ground every answer in the document. Call read_document to quote or check wording, and \
cite section ids in square brackets, e.g. [S8], for anything you assert about what the \
document says.
- Never do arithmetic yourself. deal_terms gives you every derived percentage; model_exits \
runs any exit through the waterfall; outcome_analysis prices an outcome for each side. Call \
them and quote the results. If a question needs a number you cannot get from a tool, say so.
- The document contradicts itself in several places, all catalogued by list_findings. When a \
question touches one, say which reading you are using and what the alternative gives. Do not \
silently pick one.
- Distinguish clearly between: what the document states, what follows arithmetically from it, \
and what is your judgement. Label judgement as judgement.
- Be concise and concrete. Lead with the answer. Dollar figures in $M to two decimals, shares \
as percentages to one decimal. No preamble, no recap of the question.
- If the document simply does not address something - and it leaves a lot open - say that \
plainly and point at the nearest finding rather than inventing a market-standard answer."""


class Answerer(Protocol):
    def ask(self, question: str) -> str: ...


@dataclass
class ClaudeAnswerer:
    """Claude, with the deal model available as tools."""

    model: str = DEFAULT_MODEL
    api_key: str = field(default_factory=lambda: os.environ.get("ANTHROPIC_API_KEY", ""))
    max_turns: int = 8
    #: The running conversation, so a REPL can ask follow-up questions.
    history: list[dict[str, Any]] = field(default_factory=list)
    verbose: bool = False

    def ask(self, question: str) -> str:
        import anthropic  # imported here so the offline path needs no dependency

        client = anthropic.Anthropic(api_key=self.api_key or None)
        self.history.append({"role": "user", "content": question})

        for _ in range(self.max_turns):
            response = client.messages.create(
                model=self.model,
                max_tokens=2000,
                system=SYSTEM_PROMPT,
                tools=tools.TOOL_SCHEMAS,
                messages=self.history,
            )
            self.history.append({"role": "assistant", "content": response.content})

            if response.stop_reason != "tool_use":
                return "".join(
                    block.text for block in response.content if block.type == "text"
                ).strip()

            results = []
            for block in response.content:
                if block.type != "tool_use":
                    continue
                if self.verbose:
                    print(f"  [tool] {block.name}({block.input})")
                results.append(
                    {
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": tools.call(block.name, dict(block.input)),
                    }
                )
            self.history.append({"role": "user", "content": results})

        return "Gave up after too many tool calls without reaching an answer."


@dataclass
class OfflineAnswerer:
    """Rule-based answers over the same tools, for use without an API key.

    Keyword routing, deliberately shallow: it recognises the dozen questions this
    document actually raises and refuses the rest rather than guessing.
    """

    def ask(self, question: str) -> str:
        q = question.lower()
        for keywords, handler in _ROUTES:
            if any(k in q for k in keywords):
                return handler(q)
        return (
            "Offline mode cannot answer that one. It handles the cap table, the sharing "
            "ratios, the liqpref, the worked exits, arbitrary exit scenarios, outcome "
            "analysis for either side, the entity structure, and the findings register. "
            "Set ANTHROPIC_API_KEY for the full agent, or run `report` for everything at "
            "once."
        )


def _answer_cap_table(_: str) -> str:
    terms, econ = DealTerms(), derive(DealTerms())
    return (
        f"Post-ROC, Class A holds {econ.class_a_profit_share:.2%} and Class B "
        f"{econ.class_b_profit_share:.2%} of all profit above the returned capital "
        f"(2% commitment plus 30% carry on the LPs' 98%). [S1][S2]\n\n"
        f"The document states {terms.stated_post_roc_class_a:.1%} / "
        f"{terms.stated_post_roc_class_b:.1%}, which sums to 101% - the tail in [S4] "
        f"confirms 68.6% is intended (finding F1).\n\n"
        f"After the transaction, every dollar of distribution above NLP's repaid $35M "
        f"splits: Class A {econ.tail_class_a:.1%}, Class B1 (old LPs) "
        f"{econ.tail_class_b1:.1%}, NLP {econ.tail_nlp_total:.1%} - of which "
        f"{econ.tail_nlp_direct:.1%} is NLPI's direct portco stake and "
        f"{econ.tail_nlp_feeder:.1%} the feeder's Class B2. Class A is not diluted; NLP's "
        f"share comes entirely out of Class B. [S4][S10]"
    )


def _answer_liqpref(_: str) -> str:
    terms = DealTerms()
    at_x1 = pref_consistency(terms.x1_class_b)
    at_x2 = pref_consistency(terms.x2_portco)
    return (
        f"NLPF puts in ${terms.feeder_contribution:,.2f}M with a "
        f"{terms.feeder_liqpref_multiple:.2f}x pref, so the priority claim is "
        f"${terms.feeder_liqpref:,.2f}M - sized to the NLP cheque, not to the feeder's own "
        f"money. It stops ${terms.check - terms.feeder_liqpref:,.2f}M short of $35M because SB2 "
        f"cannot grant a pref over the shares it has already sold to NLPI: that slice is paid "
        f"onshore, direct, and makes up the difference. So NLP's two entities are made whole "
        f"together at exactly ${terms.check:,.2f}M of exits. [S5][S9]\n\n"
        f"The multiple is therefore derived, not negotiated: pref = (1 - NLPI's onshore share) "
        f"x $35M. At the 1.4% the document's worked exits use, that is "
        f"{at_x1['consistent_multiple']:.2f}x. At x2 = 12.6%, which is what [S5] and [S10] say "
        f"NLPI actually owns, it is {at_x2['consistent_multiple']:.2f}x "
        f"(${at_x2['consistent_pref']:,.2f}M) - and holding 9.86x there means the pref only "
        f"clears after ${at_x2['exits_until_pref_exhausted']:,.2f}M of exits, by which point NLP "
        f"has taken ${at_x2['over_recovery']:,.2f}M more than its 1x out of Class A and Class B1 "
        f"(findings F2 and F14).\n\n"
        f"Two things about the pref itself are still open: it is senior to both existing classes "
        f"and participating (F7), and nothing routes NLPF's receipts to NLPI, which funded 90% of "
        f"the cheque (F8, the document's own open question, asked twice). [S8][S9]\n\n"
        f"On the document's own split it now clears to the cent at the marker:\n\n"
        f"{tools.model_exits(exits=None, convention='doc_examples')}"
    )


def _answer_worked_exits(_: str) -> str:
    struct = tools.model_exits()
    doc = tools.model_exits(convention="doc_examples")
    return (
        "The document splits the buyer's cheque two different ways, so both are worth "
        "seeing - and since the 9.86x pref is sized off the 1.4% version, the choice now "
        "sets the pref too. At x2 = 12.6%, which is what [S5] and the tail in [S10] say:\n\n"
        f"{struct}\n\n"
        "As the worked exits in [S8] and [S9] actually compute it (98.6/1.4, substituting x1 "
        "for x2 - finding F2):\n\n"
        f"{doc}\n\n"
        "The second reproduces the document's $19.72M / $0.28M / $14.79M / $0.21M exactly, "
        "and clears the pref to the cent at the marker; the first leaves $3.92M of pref "
        "outstanding after the same $35M of exits (findings F2, F14)."
    )


def _answer_outcome(q: str) -> str:
    import re

    match = re.search(r"(\d[\d,]*\.?\d*)\s*(m|mm|million|bn|b)?", q)
    total = 360.0
    if match:
        value = float(match.group(1).replace(",", ""))
        if match.group(2) in {"bn", "b"}:
            value *= 1000
        total = value
    rows = [
        f"At ${total:,.0f}M of total future proceeds from the remaining portfolio "
        f"(the document carries it at $360M):",
        tools.outcome_analysis(total),
        "",
        "Sensitivity, Class B1 with the deal less Class B1 without it:",
    ]
    from .terms import old_lp_tradeoff

    for multiple in (0.1, 0.25, 0.5, 0.75, 1.0, 1.5):
        trade = old_lp_tradeoff(360.0 * multiple)
        rows.append(
            f"  {multiple:>4.2f}x NAV (${360.0 * multiple:7,.1f}M): "
            f"with ${trade['class_b1_with_deal']:8,.1f}M  "
            f"without ${trade['class_b1_without_deal']:8,.1f}M  "
            f"delta ${trade['difference']:+8,.1f}M"
        )
    rows.append(
        "\nThe old LPs are indifferent at about $40M of total future proceeds; above that "
        "they are buying certainty with upside, which is the 35% discount doing its work "
        "(finding F13). [S3][S4]"
    )
    return "\n".join(rows)


def _answer_structure(_: str) -> str:
    terms = DealTerms()
    return (
        f"Two entities, because only part of the cheque can go offshore-to-offshore [S5]:\n\n"
        f"- NLPF (Singapore feeder): ${terms.feeder_contribution:,.2f}M (10%) into SB2 "
        f"Mauritius as new Class B2, with a {terms.feeder_liqpref_multiple:.0f}x pref "
        f"(= ${terms.feeder_liqpref:,.2f}M) and x1 = {terms.x1_class_b:.1%} of Class B.\n"
        f"- NLPI (India fund): ${terms.onshore_contribution:,.2f}M buying x2 = "
        f"{terms.x2_portco:.1%} of SB2's stake in each portco directly onshore - "
        f"x2_we, x2_mg, x2_niyo, x2_freo, x2_kredx.\n\n"
        f"So ${terms.feeder_contribution:,.2f}M is primary capital into the fund and "
        f"${terms.onshore_contribution:,.2f}M is a secondary purchase of assets from the fund. "
        f"Delaware portcos need SHA amendments for the put/call; the India-domiciled ones need "
        f"the equivalent, and other shareholders' ROFR/tag rights are engaged either way "
        f"(F9). [S5][S7]"
    )


def _answer_findings(q: str) -> str:
    import re

    match = re.search(r"\bf(\d{1,2})\b", q)
    if match:
        return tools.list_findings(finding_id=f"F{match.group(1)}")
    if "high" in q:
        return tools.list_findings(severity="high")
    return tools.list_findings()


def _answer_price(_: str) -> str:
    terms, econ = DealTerms(), derive(DealTerms())
    return (
        f"NLP pays ${terms.check:,.2f}M for a {econ.tail_nlp_total:.1%} share of all future "
        f"profit plus a $35M priority return. The document's route to that: profit above the "
        f"ROC is ${econ.profit_above_roc:,.2f}M, the GP takes "
        f"${econ.gp_value:,.2f}M of it, so LP NAV is ${econ.lp_nav:,.2f}M (stated as ~$260M); "
        f"the cheque is {econ.nlp_pct_of_lp_undiscounted:.1%} of that, and at a "
        f"{terms.discount:.0%} discount buys {econ.nlp_pct_of_lp_discounted:.1%} of the LP - "
        f"i.e. {econ.nlp_derived_profit_share:.2%} of total profit, stated as "
        f"{terms.stated_tail_nlp:.1%}. [S3][S4]\n\n"
        f"Judgement: the priority return is not obviously priced into that discount. NLP's "
        f"$35M ranks ahead of everything, so on the document's numbers it is repaid out of "
        f"the first $35M of exits and is at 2.31x if the portfolio realises its $360M carrying "
        f"value. What the discount is actually buying is downside protection, and the LPs' "
        f"$35M of remaining ROC is what pays for it (F6, F13)."
    )


_ROUTES: tuple[tuple[tuple[str, ...], Any], ...] = (
    (("finding", "inconsistenc", "wrong", "error", "issue", "problem", "risk", "gap", "typo",
      "open question"), _answer_findings),
    (("liqpref", "liq pref", "preference", "10x", "pref"), _answer_liqpref),
    (("worked", "wheelseye", "niyo", "example exit", "20m", "$20"), _answer_worked_exits),
    (("cap table", "sharing ratio", "split", "31.4", "54.5", "14.1", "waterfall", "tail"),
     _answer_cap_table),
    (("breakeven", "break even", "indifferen", "sensitivity", "outcome", "moic", "return",
      "worth it", "give up"), _answer_outcome),
    (("entity", "entities", "nlpf", "nlpi", "feeder", "structure", "mauritius", "singapore",
      "india", "onshore"), _answer_structure),
    (("price", "discount", "35%", "valuation", "nav", "how much"), _answer_price),
    (("exit", "distribut", "model", "scenario"), _answer_worked_exits),
)


def build_answerer(prefer_model: bool = True, verbose: bool = False) -> tuple[Answerer, bool]:
    """Return (answerer, is_model_backed). Falls back to offline without a key."""
    if prefer_model and os.environ.get("ANTHROPIC_API_KEY"):
        try:
            import anthropic  # noqa: F401
        except ImportError:
            return OfflineAnswerer(), False
        return ClaudeAnswerer(verbose=verbose), True
    return OfflineAnswerer(), False


def _pref_row(onshore_pct: float) -> str:
    check = pref_consistency(onshore_pct)
    return (
        f"{check['consistent_multiple']:5.2f}x = ${check['consistent_pref']:6,.2f}M   "
        f"stated 9.86x clears after ${check['exits_until_pref_exhausted']:6,.2f}M of exits, "
        f"over-repaying NLP by ${check['over_recovery']:.2f}M"
    )


def report() -> str:
    """The standing analysis: summary, numbers, worked exits, findings."""
    terms, econ = DealTerms(), derive(DealTerms())
    parts = [
        "=" * 78,
        "SB2 / NLP SECONDARY - ANALYSIS REPORT",
        "=" * 78,
        "",
        "WHAT THE TRANSACTION IS",
        f"  NLP buys ${terms.check:,.2f}M of exposure to SB2 from its Class B LPs at a "
        f"{terms.discount:.0%} discount, taking its 1x back first and then sharing "
        f"pari-passu. It comes in through two entities: ${terms.feeder_contribution:,.2f}M "
        f"of primary into SB2 Mauritius with a {terms.feeder_liqpref_multiple:.0f}x pref, and "
        f"${terms.onshore_contribution:,.2f}M buying {terms.x2_portco:.1%} of each portco "
        f"position onshore in India.",
        "",
        "THE NUMBERS, RECOMPUTED FROM THE FUND'S PRIMITIVES",
        f"  Profit above ROC              ${econ.profit_above_roc:8,.2f}M",
        f"  GP value (2% + 30% carry)     ${econ.gp_value:8,.2f}M  ({econ.class_a_profit_share:.2%})",
        f"  Class B profit value          ${econ.class_b_profit_value:8,.2f}M  ({econ.class_b_profit_share:.2%})",
        f"  LP NAV                        ${econ.lp_nav:8,.2f}M  (document says ~$260M)",
        f"  Cheque as % of LP              {econ.nlp_pct_of_lp_undiscounted:8.2%}  (document says 13%)",
        f"  ... grossed up for discount    {econ.nlp_pct_of_lp_discounted:8.2%}  (document says 20%)",
        f"  ... as % of total profit       {econ.nlp_derived_profit_share:8.2%}  (document says 14.1%)",
        "",
        "  Post-transaction, per $1 of distribution above NLP's repaid $35M:",
        f"    Class A (GP)          {econ.tail_class_a:7.1%}   ({econ.sb2_share_class_a:.1%} of SB2's receipts)",
        f"    Class B1 (old LPs)    {econ.tail_class_b1:7.1%}   ({econ.sb2_share_class_b1:.1%} of SB2's receipts)",
        f"    NLPI (direct, onshore){econ.tail_nlp_direct:7.1%}   (taken before the fund sees it)",
        f"    NLPF (Class B2)       {econ.tail_nlp_feeder:7.1%}   ({econ.sb2_share_class_b2:.1%} of SB2's receipts)",
        "",
        "THE PREF MULTIPLE AGAINST THE SPLIT IT IS NETTED AGAINST",
        f"  rule: pref = (1 - NLPI's onshore share) x ${terms.check:,.2f}M",
        f"  at x1 =  1.4% (the worked exits)   {_pref_row(terms.x1_class_b)}",
        f"  at x2 = 12.6% (the structure)      {_pref_row(terms.x2_portco)}",
        "",
        "THE DOCUMENT'S WORKED EXITS, AS THE DOCUMENT COMPUTES THEM",
        tools.model_exits(convention="doc_examples"),
        "",
        "THE SAME EXITS AT x2 = 12.6%, WHICH IS WHAT THE STRUCTURE SAYS",
        tools.model_exits(),
        "",
        "WHAT EACH SIDE MAKES",
        _answer_outcome("360"),
        "",
        "=" * 78,
        f"FINDINGS ({sum(1 for f in FINDINGS if f.severity == 'high')} high, "
        f"{sum(1 for f in FINDINGS if f.severity == 'medium')} medium, "
        f"{sum(1 for f in FINDINGS if f.severity == 'low')} low)",
        "=" * 78,
        "",
        tools.list_findings(),
    ]
    return "\n".join(parts)
